"Documentation":
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

"Modules":
  - changed-files:
    - any-glob-to-any-file:
      - 'modules/**'
      - '**/*.tf'

"Examples":
  - changed-files:
    - any-glob-to-any-file:
      - 'examples/**'

"Tests":
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - '**/*_test.tf'

"CI":
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '.github/workflows/**'
      - '.github/dependabot.yml'

"Security":
  - changed-files:
    - any-glob-to-any-file:
      - 'SECURITY.md'
      - '.github/dependabot.yml'
