"type:docs":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
          - "LICENSE*"
          - "CHANGELOG*"

"type:chore":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".pre-commit-config.yaml"
          - ".gitignore"
          - ".editorconfig"
          - "renovate.json"
          - "dependabot.yml"

"type:feature":
  - changed-files:
      - any-glob-to-any-file:
          - "*.tf"
          - "modules/**/*.tf"

"type:bug":
  - changed-files:
      - any-glob-to-any-file:
          - "*.tf"
          - "modules/**/*.tf"

"type:spike":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"

"type:tests":
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
          - "modules/**/tests/**"
          - "**/*.tftest.hcl"
